# .readthedocs.yaml

version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
    nodejs: "20"
  jobs:
    pre_create_environment:
      - npm -g i @mermaid-js/mermaid-cli

sphinx:
  configuration: src/conf.py

python:
  install:
    - requirements: requirements.txt
